"""added image url in post table

Revision ID: 403afc1ba5b6
Revises: 9bc871825cdc
Create Date: 2026-09-07 03:07:48.108116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '403afc1ba5b6'
down_revision: Union[str, Sequence[str], None] = '9bc871825cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('cover_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'cover_image_url')
    # ### end Alembic commands ###
