"""add category to posts

Revision ID: 83e49642e5d2
Revises: cb1bc39bf2d1
Create Date: 2026-09-19 22:46:17.413930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '83e49642e5d2'
down_revision: Union[str, Sequence[str], None] = 'cb1bc39bf2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(
        'posts_category_id_fkey',
        'posts',
        'categories',
        ['category_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_category_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    # ### end Alembic commands ###
