"""removed post likes

Revision ID: 9bc871825cdc
Revises: 76a5183a0ee3
Create Date: 2026-09-07 03:00:33.054403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '9bc871825cdc'
down_revision: Union[str, Sequence[str], None] = '76a5183a0ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'likes_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
