"""cascade post dependents on delete

Revision ID: cb1bc39bf2d1
Revises: 403afc1ba5b6
Create Date: 2026-09-13 22:11:58.728422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'cb1bc39bf2d1'
down_revision: Union[str, Sequence[str], None] = '403afc1ba5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_post_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('post_likes_post_id_fkey'), 'post_likes', type_='foreignkey')
    op.create_foreign_key('post_likes_post_id_fkey', 'post_likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('post_tags_post_id_fkey'), 'post_tags', type_='foreignkey')
    op.create_foreign_key('post_tags_post_id_fkey', 'post_tags', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_tags_post_id_fkey', 'post_tags', type_='foreignkey')
    op.create_foreign_key(op.f('post_tags_post_id_fkey'), 'post_tags', 'posts', ['post_id'], ['id'])
    op.drop_constraint('post_likes_post_id_fkey', 'post_likes', type_='foreignkey')
    op.create_foreign_key(op.f('post_likes_post_id_fkey'), 'post_likes', 'posts', ['post_id'], ['id'])
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_post_id_fkey'), 'comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
